# Generated by Django 3.0.2 on 2020-01-26 04:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('costperday', models.IntegerField()),
                ('places', jsonfield.fields.JSONField(default=dict)),
                ('hotels', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
