# Generated by Django 3.0.2 on 2020-01-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='costperday',
        ),
    ]
